# Generated by Django 5.0.6 on 2025-04-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardId', models.AutoField(primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=100)),
                ('cardDesc', models.TextField()),
            ],
            options={
                'db_table': 'Card',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionId', models.AutoField(primary_key=True, serialize=False)),
                ('sessionYear', models.PositiveSmallIntegerField(max_length=4)),
                ('sessionQuarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.CreateModel(
            name='SessionAssignment',
            fields=[
                ('sessionAssignId', models.AutoField(primary_key=True, serialize=False)),
                ('additionalComments', models.TextField()),
                ('sessionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isAssigned', to='quiz.session')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasSessions', to='core.user')),
            ],
            options={
                'db_table': 'Session_Assignment',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(3, 3), (1, 1), (2, 2)], max_length=1)),
                ('progress', models.IntegerField(choices=[(3, 3), (1, 1), (2, 2)], max_length=1)),
                ('cardId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BelongsTo', to='quiz.card')),
                ('sessionAssignId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasSession', to='quiz.sessionassignment')),
            ],
            options={
                'db_table': 'Vote',
            },
        ),
    ]
