# Generated by Django 5.0.6 on 2025-04-12 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionYear',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='progress',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
